version: '2.1'
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: 'rpg'
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-U', 'postgres']
      interval: 5s
      timeout: 1s
      retries: 2